export const INNER__BANNER = [
  {
    id: 0,
    className: "item",
    alt: `item0`,
    src: `./images/slides/main0.jpg`,
    title: "I LuBean You",
    desc: "러빈만의 철학이 담긴 원두를 만나보세요",
  },
  {
    id: 1,
    className: "item",
    alt: `item1`,
    src: `./images/slides/main1.jpg`,
    title: "러빈의 이유있는 고집",
    desc: "이상적인 기후의 고지대에서 생산",
  },
  {
    id: 2,
    className: "item",
    alt: `item2`,
    src: `./images/slides/main2.jpg`,
    title: "최고의 커피, 그 이상의 가치",
    desc: "한 잔의 완벽한 커피를 위한 끊임없는 연구",
  },
  {
    id: 3,
    className: "item",
    alt: `item3`,
    src: `./images/slides/main3.jpg`,
    title: "NEW CROP 출시 예정",
    desc: "따뜻한 바람이 내 마음을 감싸안은 듯한 평온함",
  },
  {
    id: 4,
    className: "item",
    alt: `item4`,
    src: `./images/slides/main4.jpg`,
    title: "원두쓰리,원두쓰리,,",
    desc: "최상의 풍미를 자랑하는 아라비카 원두",
  },
];

export const INNER__PRODUCT = [
  {
    id: 1,
    name: "산 안토니오 챠기테 [강배전]",
    desc: "San Antonio Chaguite",
    country_name: "과테말라",
    weight: "200g",
    tag: ["new"],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 2,
    name: "폰테 알타 내추럴",
    desc: "Ponte Alta Natural",
    country_name: "브라질",
    weight: "100g",
    tag: ["new", "best"],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 3,
    name: "라 벤디시온 파카마라 내추럴",
    desc: "La Bendicion Pacamara Natural",
    country_name: "니카라과",
    weight: "100g",
    tag: ["new"],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 4,
    name: "보카 [강배전]",
    desc: "파푸아뉴기니",
    country_name: "보카",
    weight: "100g",
    tag: [],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 5,
    name: "배드블러드",
    desc: "La Bendicion Pacamara Natural",
    country_name: "보카",
    weight: "100g",
    tag: [],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 6,
    name: "니카라과",
    desc: "파푸아뉴기니",
    country_name: "보카",
    weight: "100g",
    tag: [],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 7,
    name: "보카 [강배전]",
    desc: "La Bendicion Pacamara Natural",
    country_name: "파푸아뉴기니",
    weight: "100g",
    tag: [],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 8,
    name: "라스 라하스 펠라 네그라",
    desc: "과테말라",
    country_name: "파푸아뉴기니",
    weight: "100g",
    tag: ["best"],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 9,
    name: "폰테 알타 내추럴",
    desc: "Ponte Alta Natural",
    country_name: "브라질",
    weight: "100g",
    tag: [],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 10,
    name: "라 벤디시온 파카마라 내추럴",
    desc: "La Bendicion Pacamara Natural",
    country_name: "니카라과",
    weight: "100g",
    tag: [],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 11,
    name: "누에바 루즈 파라이네마",
    desc: "파푸아뉴기니",
    country_name: "파푸아뉴기니",
    weight: "100g",
    tag: ["best"],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
  {
    id: 12,
    name: "배드블러드",
    desc: "La Bendicion Pacamara Natural",
    country_name: "보카",
    weight: "100g",
    tag: [],
    price: `${Math.ceil(Math.random() * 99)}000`,
    menus: "singleOrigin",
    imgUrl: [
      "/images/products/coffee_pkg_1.jpeg",
      "/images/products/coffee_pkg_2.jpeg",
    ],
  },
];
